import type { Metadata } from "next";
import "./globals.css";
import LeftSideBar from "./(components)/LeftSideBar";
import AuthProvider from "./(components)/AuthProvider";
import PublicTopbar from "./(components)/PublicTopbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <PublicTopbar />
        <AuthProvider>
          <div className="m-2">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
