"use client"
import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "react-redux";
import { persistor, store } from "./api/store/store";
import { PersistGate } from "redux-persist/integration/react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50"><Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        {children}
      </PersistGate>
    </Provider></body>
    </html>
  );
}
